DISTORTION: MSE
LAMBDA: 0.0075
NUM_FILTERS: 128
N_GMM: 3
PRIOR: "context"
SHALLOW: false
HEATMAP: false
DATASET:
  TRAIN_ROOT: "/path/to/ImageNet/train"
  TRAIN_PATH: "../../datasets/ImageNetAll.txt"

TRAIN:
  MASKLOSS: false
  CHECKPOINT_DIR:
  MAIN_LR: 0.0001
  WORKERS: 8
  BATCH_SIZE: 8
  PATCH_SIZE: 256
  ITERATIONS: 1000000
  DECAYED_ITERATIONS: 80000
  DECAY_FACTOR: 0.1
  FIX_QUA: false
  QUANTIZE_ENT: "U-Q"
  QUANTIZE_DEC: "STE-Q"
  QUANTIZE_HA:
  # SRA-Q
  TAU_DECAY_FACTOR: 0.0003
  TAU_DECAY_ITERATION: 990000
  # DS-Q
  K_INIT: 0.1
  K_ITERATION: 990000
  K_END: 0.1
  MODULE_LIST:
   - ent
   - hdec
   - dec
   - cent
